<?php


$pastas = ['A_BELA_E_A_FERA',
'ALICE_NO_PAÍS_DAS_MARAVILHAS','ANGRY_BIRDS','A_PEQUENA_SEREIA', 'ATLÉTICO_MINEIRO', 'BABY_DISNEY', 'BACKYARDIGANS', 'BAILARINA_PERSONALIZADA', 'BAILARINA_PRETA_E_ROSA_PERSONALIZADA', 'BAILARINA_PROVENÇAL_PERSONALIZADA', 'BAMBAM_E_PEDRITA', 'BARBIE_PROVENÇAL', 'BEN_10', 'BIG_HERO', 'BONECAS', 'BRANCA_DE_NEVE', 'BRUXINHA', 'CARROS', 'CARROS_CLEAN', 'CARROSSEL', 'CHAPEUZINHO_VERMELHO', 'CHAVES', 'CIRCO', 'CIRCO_VINTAGE', 'COPA_DO_MUNDO', 'CORUJINHA_PROVENÇAL', 'CRUZEIRO', 'DINOSSAUROS', 'DISNEY_STORE', 'DISNEY', 'DIVA', 'DIVERTIDAMENTE', 'ENROLADOS', 'FAZENDINHA', 'FAZENDINHA_ROSA', 'FESTA_TEEN_NEON', 'FESTA_VINTAGE_PERSONALIZADA', 'FROZEN', 'FUNDO_DO_MAR', 'GALINHA_PINTADINHA', 'GATINHA_MARRIE', 'HALLOWEEN', 'HOMEM_ARANHA','HOT_WHELLS','JAKE_E_OS_PIRATAS','JARDIM_ENCANTADO','JOANINHA','LEGO','LIGA_DA_JUSTIÇA','MADAGASCAR','MELHOR_IDADE','MICKEY','MICKEY_E_MINNIE','MINECRAFT','MINIONS','MINNIE','MINNIE_VERMELHA','MINNIE_VERMELHA_PERSONALIZADA','MIRACULOS','MONSTER_HIGH','MONSTER_HIGH_PERSONALIZDO','MORANGUINHO','NOVA_CINDERELA_PERSONALIZADA','PASSARINHOS','PATATI_E_PATATA','PEPA_PIG','PEQUENO_PRÍNCIPE','PETER_PAN','PRINCESA_SOFIA','PIRATAS','PIRATAS_DO_CARIBE','PRAIA','PRINCESAS','PRINCESAS_PERSONALIZADO','REINADO_DA_CINDERELA','REINADO_DA_MINNIE','REINADO_MENINA','REINADO_MENINO','REINADO_URSO','REI_ARTHUR','SAFARI_BABY','SAFARI_DISNEY','SCOOBY_DOO','SININHO','SOLDADINHO_DE_CHUMBO','STAR_WARS','TEAN_NEON','TINKER_BELL','VINGADORES'];

foreach($pastas as $id){
    mkdir($id);
}

?>